baseURL = '/'
locale = 'en-us'
title = 'Welcome to My photosite'
theme = "PaperMod"

[markup.goldmark.renderer]
    unsafe = true

# navigation
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Main entry
[[menu.main]]
    name = "Photography"
    identifier = "Photography"
    url = "/photography/"
    weight = 2

# Parent link
[[menu.main]]
    name = "Football & Sports"
    url = "/photography/football_sports/"
    parent = "Photography" # must match the above identifier
    weight = 1

[[menu.main]]
  name = "Nature & Beauty"
  url = "/photography/nature_beauty/"
  parent = "Photography"      
  weight = 2

[[menu.main]]
  name = "Racing"
  url = "/photography/racing/"
  parent = "Photography"      
  weight = 3

[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":git"]
